# NumPy

**What is it?**
- a librry in Python for numerical computing

**What does it do?**
- Array handling: ndarray creates array of different dimensions & perform operation on them

- Maths operation

- Broadcasting: Allows you to perform operations on arrays of different shapes

- Array indexing and slicing

- Statistical and aggregation functions

- Random number generation

- Interfacing with other libraries: 
    * Panda - DA
    * matplotlib - plotting
    * SciPy = scientific computing

- Performance

# ndarray
- it's a multidimensional array object

- it's a generic multidimensional container for homogenous data 

- all elements must be the SAME type

- every array has a data shape: tuple indicates the size of each dimension

- dtype describes the data type

- common terms:
    * array
    * NumPy array
    * ndarray

In [8]:
# basic numerical operation

import numpy as np

data = np.array ([[2.2, -0.5, 88], [100, 7.3, -4]])

print(data)

darab = data * 33
tambah = data + data

print(f'\nHasil darab: {darab}')
print(f'\nHasil tambah: {tambah}')

[[  2.2  -0.5  88. ]
 [100.    7.3  -4. ]]

Hasil darab: [[  72.6  -16.5 2904. ]
 [3300.   240.9 -132. ]]

Hasil tambah: [[  4.4  -1.  176. ]
 [200.   14.6  -8. ]]


In [11]:
print(f'Data shape: {data.shape}\n')
print(f'Data type: {data.dtype}')

Data shape: (2, 3)

Data type: float64


**Creating ndarray**
- array function
- example below shows how 42, 22 and 0 are upcasted to match data type of pi value.
- this is done to make sure the entire array is homogenous

In [17]:
#np.array creates homogenous array

data_1 = [42, 3.14159, 22, 0]

arr_1 = np.array(data_1)

print(arr_1)
print(arr_1.shape)
print(arr_1.dtype)

[42.       3.14159 22.       0.     ]
(4,)
float64


In [22]:
data_2 = [[9, 8, 7, 6, 5], [4, 3, 2, 1, 0]]

arr_2 = np.array(data_2)

print(arr_2)
print(arr_2.shape)
print(arr_2.dtype)

[[9 8 7 6 5]
 [4 3 2 1 0]]
(2, 5)
int32


In [26]:
# create arrays

kosong = np.zeros(20)
print(kosong)

higher_dimensional_array1 = np.zeros((2,5))
print('\nHigher Dimensioanl array 1:')
print(higher_dimensional_array1)

higher_dimensional_array2 = np.zeros((6,3))
print('\nHigher Dimensioanl array 2:')
print(higher_dimensional_array2)


higher_dimensional_array3 = np.zeros((4,9))
print('\nHigher Dimensioanl array 3:')
print(higher_dimensional_array3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Higher Dimensioanl array 1:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Higher Dimensioanl array 2:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Higher Dimensioanl array 3:
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [29]:
np.arange(51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

**NumPy Data Types**

- Link: https://wesmckinney.com/book/numpy-basics#tbl-table_array_dtypes

    - int

    - float

    - complex

    - bool

    - object

    - string_
    
    - unicode

- Data type can be changed using astype() method

In [36]:
# cast integers to floating point

array = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
print(array)
print(array.dtype)

convert_array_float = array.astype(np.float32)
print(convert_array_float)
print(convert_array_float.dtype)

[9 8 7 6 5 4 3 2 1 0]
int32
[9. 8. 7. 6. 5. 4. 3. 2. 1. 0.]
float32


In [39]:
# cast floating point to integers

floating_num = np.array([1.2, 7.8, 5.35, 0.33, 22.6])
print(floating_num)
print(floating_num.dtype)

convert_array_int = floating_num.astype(np.int64)
print(convert_array_int)
print(convert_array_int.dtype)

[ 1.2   7.8   5.35  0.33 22.6 ]
float64
[ 1  7  5  0 22]
int64


In [44]:
# cast strings to numeric form
strings = np.array(['1.2', '7.8', '5.35', '0.33', '22.6'], dtype=np.string_)
print(strings)
print(strings.dtype)

numeric_strings = strings.astype(float)
print(numeric_strings)
print(numeric_strings.dtype)


[b'1.2' b'7.8' b'5.35' b'0.33' b'22.6']
|S4
[ 1.2   7.8   5.35  0.33 22.6 ]
float64
