# Vectorization

**Arithmetic Operations**
- arrays are important as it allows you to express batch operations on data without writing any for loops
- This is called vectorization
- any arithmetic operations between equal-size arrays apply the operation element-wise

**OTHER ARRAY OPERATIONS**
* Basic indexing and slicing
* Indexing with slices
* Boolean Indexing
* Fanyc Indexing
* Transposing Arrays and Swapping Exes


In [7]:
import numpy as np
data = np.array ([[2.2, 5.0, 8.1], [100, 7.3, 4]])
print(data)

print('\nArithmetic operations:')

darab = data * data
print(darab)

tolak = data - data 
print(tolak)

bahagi = data / 99
print(bahagi)

kuasa2 = data ** 2
print(kuasa2)

boolVal = 

[[  2.2   5.    8.1]
 [100.    7.3   4. ]]

Arithmetic operations:
[[4.840e+00 2.500e+01 6.561e+01]
 [1.000e+04 5.329e+01 1.600e+01]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0.02222222 0.05050505 0.08181818]
 [1.01010101 0.07373737 0.04040404]]
[[4.840e+00 2.500e+01 6.561e+01]
 [1.000e+04 5.329e+01 1.600e+01]]


In [10]:
data2 = np.array ([[2.2, -0.5, 88], [100, 7.3, -4]])
data2 < data

array([[False,  True, False],
       [False, False,  True]])

# Pesudorandom Number Generation

- numpy.random generates arrays of sample values from many kinds of probability distribution

- list of methods: https://wesmckinney.com/book/numpy-basics#tbl-table_numpy_random


In [13]:
samples = np.random.standard_normal(size=(6, 10))
samples

array([[-1.86867901,  1.4103654 , -0.0705822 , -1.18329691,  0.17824098,
        -0.9618206 ,  2.03616193,  1.20335225, -0.39375663,  1.66300437],
       [-0.57792277, -0.85589486, -1.51082469,  0.04269883, -0.92017325,
        -1.62275234,  1.67104053,  0.29041975,  0.19093228,  0.28857731],
       [-0.75279362, -0.80770787, -0.95082855,  2.20355575,  0.07623348,
         0.18666309, -0.79530531, -0.13953321,  2.14435506, -0.31074555],
       [ 0.0630885 , -0.71974764,  1.48759922,  0.45232436,  1.09055021,
        -0.62255885,  1.36064425,  0.20679871, -1.23890856,  0.04080928],
       [ 0.21511738, -0.73731797, -0.85105773, -0.57903171, -0.6077658 ,
         1.04009514, -1.02258925, -0.45723095,  0.32401809, -0.24232376],
       [-1.0968125 ,  0.63023041,  1.10857369,  0.5342026 ,  0.84504013,
         0.90171188, -0.62041288, -0.44064981, -1.16967758, -0.50709232]])

# Universal Functions

- ufunc is a function that performs element-wise operations on data in ndarrays

- it's a vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results

- ufunc functions: https://wesmckinney.com/book/numpy-basics#tbl-table_unary_ufuncs

- binary universal functions: https://wesmckinney.com/book/numpy-basics#tbl-table_binary_ufuncs

# Array-Oriented Programming with Arrays

- numpy arrays allows us to express daya processing tasks as concise array expressions that might otherwise require writing loops

- This is called vectorization


# Expressing Conditional Logic as Array Operations

# Mathematical and Statistical Methods

- basic array statistical methods: https://wesmckinney.com/book/numpy-basics#tbl-table_statistical_methods

    * sum 
    * mean
    * std, var
    * min, max
    * argmin, argmax
    * cumsum
    * cumprod

In [26]:
import numpy as np

rng = np.random.default_rng()

array = rng.standard_normal((3,7))

print(f'Array:\n{array}')
print('\nMean:')
print(array.mean())

print('\nSum:')
print(array.sum())

#optional axis argument
print('\nAxis argument(Optional):')

print('\ncomputes mean across columns:')
print(array.mean(axis=1))         

print('\ncomputes sum down the rows:')
print(array.sum(axis=0))              

Array:
[[-1.01414903 -0.85059668  2.2843603  -0.96641106  0.3847066  -0.87614357
   0.53867621]
 [-0.9748435   0.44438725 -0.46064132  0.03603637  0.98254735 -0.8291739
  -0.47591484]
 [ 0.25829228 -0.58938209  1.42458652 -0.81168824 -0.10529955  0.39610062
   0.39900423]]

Mean:
-0.03835933565167321

Sum:
-0.8055460486851374

Axis argument(Optional):

computes mean across columns:
[-0.07136532 -0.18251466  0.13880197]

computes sum down the rows:
[-1.73070024 -0.99559152  3.2483055  -1.74206293  1.2619544  -1.30921685
  0.4617656 ]


**CUMSUM**

In [27]:
arr_cumsum = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1])
print(arr_cumsum.cumsum())

[ 9 17 24 30 35 39 42 44 45]


**CUMSUM - MULTIDIMENSIONAL ARRAY**

In [31]:
md_array = np.array([[2, 4, 6], [3, 6, 9], [4, 8, 12]])

print(md_array)

print('\ncomputes cumsum across columns:\n')
print(md_array.cumsum(axis = 1))

print('\ncomputes cumsum across rows:\n')
print(md_array.cumsum(axis = 0))

[[ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]]

computes cumsum across columns:

[[ 2  6 12]
 [ 3  9 18]
 [ 4 12 24]]

computes cumsum across rows:

[[ 2  4  6]
 [ 5 10 15]
 [ 9 18 27]]


* Methods for Boolean Arrays

* sorting

* Unique and other Set logic: 
    * https://wesmckinney.com/book/numpy-basics#tbl-table_setops

* File Input and Output with Arrays

* Linear Algebra: 
    * https://wesmckinney.com/book/numpy-basics#tbl-table_numpy_linalg
